group: edge
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

nstall: true
before_script:
  - nvm install 6

script:
  - bash gradlew clean build
  - bash gradlew dependencyUpdates -Drevision=release

cache:
  directories:
    - web/node_modules/
    - $HOME/.gradle/
    - .gradle/
